_jit_bailout_depth: 2
_jit_fuser: fuser1
_jit_fusion_strategy:
- !!python/tuple
  - DYNAMIC
  - 3
allow_tf32: true
append: false
avg_num_neighbors: 7.511111111111111
batch_size: 1
chemical_embedding_irreps_out: 16x0e
chemical_symbols:
- H
- O
- C
- N
code_commits:
  nequip: 81a4db44dd076d213749ad0743dea99428dd8ebe
conv_to_output_hidden_irreps_out: 8x0e
dataloader_num_workers: 0
dataset: npz
dataset_AtomicData_options:
  r_max: 4.0
dataset_file_name: ./benchmark_data/rxn0015-train.npz
dataset_seed: 456
dataset_statistics_stride: 1
default_dtype: float64
device: cpu
e3nn_version: 0.5.6
early_stopping: null
early_stopping_kwargs: null
ema_decay: 0.999
ema_use_num_updates: true
end_of_batch_callbacks: []
end_of_epoch_callbacks: []
end_of_train_callbacks: []
equivariance_test: false
exclude_keys: []
feature_irreps_hidden: 16x0e+16x1e+16x2e+16x0o+16x1o+16x2o
final_callbacks: []
gpu_oom_offload: false
grad_anomaly_mode: false
init_callbacks: []
irreps_edge_sh: 1x0e+1x1o+1x2e
key_mapping:
  E: total_energy
  F: forces
  R: pos
  z: atomic_numbers
l_max: 2
learning_rate: 0.01
log_batch_freq: 100
log_epoch_freq: 1
loss_coeffs: forces
lr_scheduler_kwargs: {}
lr_scheduler_name: none
max_epochs: 200
max_gradient_norm: .inf
metrics_components: null
metrics_key: validation_loss
model_builders:
- SimpleIrrepsConfig
- EnergyModel
- PerSpeciesRescale
- StressForceOutput
- RescaleEnergyEtc
model_debug_mode: false
model_dtype: float32
n_train: 5
n_train_per_epoch: null
n_val: 5
nequip_version: 0.6.2
npz_fixed_field_keys:
- atomic_numbers
num_basis: 8
num_features: 16
num_types: 4
optimizer_kwargs:
  amsgrad: false
  betas: !!python/tuple
  - 0.9
  - 0.999
  capturable: false
  differentiable: false
  eps: 1.0e-08
  foreach: null
  fused: null
  maximize: false
  weight_decay: 0
optimizer_name: Adam
parity: true
r_max: 4.0
report_init_validation: true
root: results/rxn0015
run_name: rxn0015
save_checkpoint_freq: -1
save_ema_checkpoint_freq: -1
seed: 123
shuffle: true
start_of_epoch_callbacks: []
tensorboard: false
torch_version: !!python/object/new:torch.torch_version.TorchVersion
- 2.6.0
train_idcs: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
    ZQpxAVgKAAAANDg4NzkzOTI4MHECWAMAAABjcHVxA0t7TnRxBFEugAJdcQBYCgAAADQ4ODc5Mzky
    ODBxAWEuewAAAAAAAABJAAAAAAAAACwAAAAAAAAAdQAAAAAAAAAEAAAAAAAAADkAAAAAAAAAQgAA
    AAAAAAAKAAAAAAAAAGUAAAAAAAAAbgAAAAAAAABxAAAAAAAAAD0AAAAAAAAAeAAAAAAAAAADAAAA
    AAAAAGwAAAAAAAAAEQAAAAAAAABnAAAAAAAAAAUAAAAAAAAAdgAAAAAAAAA0AAAAAAAAADsAAAAA
    AAAASwAAAAAAAABMAAAAAAAAABgAAAAAAAAAWQAAAAAAAABbAAAAAAAAACkAAAAAAAAAXwAAAAAA
    AAAGAAAAAAAAAEoAAAAAAAAATQAAAAAAAABYAAAAAAAAAE8AAAAAAAAAMwAAAAAAAAAXAAAAAAAA
    ACIAAAAAAAAAEwAAAAAAAABoAAAAAAAAAA8AAAAAAAAACwAAAAAAAABrAAAAAAAAACcAAAAAAAAA
    UgAAAAAAAAAWAAAAAAAAAHIAAAAAAAAAMgAAAAAAAAAhAAAAAAAAAAEAAAAAAAAALgAAAAAAAAAV
    AAAAAAAAAAgAAAAAAAAAaQAAAAAAAAAbAAAAAAAAAHoAAAAAAAAAdAAAAAAAAAAaAAAAAAAAAGoA
    AAAAAAAAVgAAAAAAAABEAAAAAAAAAHAAAAAAAAAARQAAAAAAAABaAAAAAAAAADUAAAAAAAAAeQAA
    AAAAAAA/AAAAAAAAACsAAAAAAAAASAAAAAAAAABHAAAAAAAAADcAAAAAAAAAZgAAAAAAAAAOAAAA
    AAAAAAAAAAAAAAAABwAAAAAAAAAgAAAAAAAAAF4AAAAAAAAAVQAAAAAAAAB3AAAAAAAAACQAAAAA
    AAAAMAAAAAAAAABAAAAAAAAAAB0AAAAAAAAAJgAAAAAAAABUAAAAAAAAABQAAAAAAAAAbQAAAAAA
    AABgAAAAAAAAAEMAAAAAAAAAPgAAAAAAAAAZAAAAAAAAADEAAAAAAAAAYgAAAAAAAAA2AAAAAAAA
    AAIAAAAAAAAALwAAAAAAAAAlAAAAAAAAAFwAAAAAAAAAYwAAAAAAAAAJAAAAAAAAAGEAAAAAAAAA
    LQAAAAAAAAAMAAAAAAAAAA0AAAAAAAAARgAAAAAAAABRAAAAAAAAAGQAAAAAAAAAKAAAAAAAAAAf
    AAAAAAAAABAAAAAAAAAATgAAAAAAAAAeAAAAAAAAAHMAAAAAAAAAbwAAAAAAAAA8AAAAAAAAAFAA
    AAAAAAAAOAAAAAAAAABTAAAAAAAAACMAAAAAAAAAVwAAAAAAAAASAAAAAAAAACoAAAAAAAAAQQAA
    AAAAAAAcAAAAAAAAADoAAAAAAAAAXQAAAAAAAAA=
- 0
- !!python/tuple
  - 5
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
train_on_keys:
- forces
train_val_split: random
type_names:
- H
- C
- N
- O
type_to_chemical_symbol:
  0: H
  1: C
  2: N
  3: O
use_ema: false
val_idcs: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
    ZQpxAVgKAAAANDg4NzkzOTI4MHECWAMAAABjcHVxA0t7TnRxBFEugAJdcQBYCgAAADQ4ODc5Mzky
    ODBxAWEuewAAAAAAAABJAAAAAAAAACwAAAAAAAAAdQAAAAAAAAAEAAAAAAAAADkAAAAAAAAAQgAA
    AAAAAAAKAAAAAAAAAGUAAAAAAAAAbgAAAAAAAABxAAAAAAAAAD0AAAAAAAAAeAAAAAAAAAADAAAA
    AAAAAGwAAAAAAAAAEQAAAAAAAABnAAAAAAAAAAUAAAAAAAAAdgAAAAAAAAA0AAAAAAAAADsAAAAA
    AAAASwAAAAAAAABMAAAAAAAAABgAAAAAAAAAWQAAAAAAAABbAAAAAAAAACkAAAAAAAAAXwAAAAAA
    AAAGAAAAAAAAAEoAAAAAAAAATQAAAAAAAABYAAAAAAAAAE8AAAAAAAAAMwAAAAAAAAAXAAAAAAAA
    ACIAAAAAAAAAEwAAAAAAAABoAAAAAAAAAA8AAAAAAAAACwAAAAAAAABrAAAAAAAAACcAAAAAAAAA
    UgAAAAAAAAAWAAAAAAAAAHIAAAAAAAAAMgAAAAAAAAAhAAAAAAAAAAEAAAAAAAAALgAAAAAAAAAV
    AAAAAAAAAAgAAAAAAAAAaQAAAAAAAAAbAAAAAAAAAHoAAAAAAAAAdAAAAAAAAAAaAAAAAAAAAGoA
    AAAAAAAAVgAAAAAAAABEAAAAAAAAAHAAAAAAAAAARQAAAAAAAABaAAAAAAAAADUAAAAAAAAAeQAA
    AAAAAAA/AAAAAAAAACsAAAAAAAAASAAAAAAAAABHAAAAAAAAADcAAAAAAAAAZgAAAAAAAAAOAAAA
    AAAAAAAAAAAAAAAABwAAAAAAAAAgAAAAAAAAAF4AAAAAAAAAVQAAAAAAAAB3AAAAAAAAACQAAAAA
    AAAAMAAAAAAAAABAAAAAAAAAAB0AAAAAAAAAJgAAAAAAAABUAAAAAAAAABQAAAAAAAAAbQAAAAAA
    AABgAAAAAAAAAEMAAAAAAAAAPgAAAAAAAAAZAAAAAAAAADEAAAAAAAAAYgAAAAAAAAA2AAAAAAAA
    AAIAAAAAAAAALwAAAAAAAAAlAAAAAAAAAFwAAAAAAAAAYwAAAAAAAAAJAAAAAAAAAGEAAAAAAAAA
    LQAAAAAAAAAMAAAAAAAAAA0AAAAAAAAARgAAAAAAAABRAAAAAAAAAGQAAAAAAAAAKAAAAAAAAAAf
    AAAAAAAAABAAAAAAAAAATgAAAAAAAAAeAAAAAAAAAHMAAAAAAAAAbwAAAAAAAAA8AAAAAAAAAFAA
    AAAAAAAAOAAAAAAAAABTAAAAAAAAACMAAAAAAAAAVwAAAAAAAAASAAAAAAAAACoAAAAAAAAAQQAA
    AAAAAAAcAAAAAAAAADoAAAAAAAAAXQAAAAAAAAA=
- 5
- !!python/tuple
  - 5
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
validation_batch_size: 5
var_num_neighbors: 0.7574545357560237
verbose: INFO
wandb: false
warn_unused: false
